version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"

python:
    install:
        path: .
        requirements: docs/requirements.txt
        method: pip

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
